DATA:
    BATCH_SIZE: 4  # per GPU
    BATCH_SIZE_VAL: 1  # per GPU
    DATASET: 'PascalContext' # dataset name
    DATA_PATH: '/home/ssd3/wutianyi/datasets/pascal_context'
    IMAGE_SIZE: 480
    NUM_CLASSES: 
MODEL:
    TYPE: SETR
    NAME: SETR
    PRETRAINED: './vit_base_patch16_224.pdparams'
    TRANS:
        PATCH_SIZE: 16
        HIDDEN_SIZE: 768
        MLP_RATIO: 4     # same as mlp_ratio = 4.0
        NUM_HEADS: 12    # 12(Base), 16(Large), 16(Huge)
        NUM_LAYERS: 12   # 12(Base), 24(Large), 32(Huge)
        QKV_BIAS: True
    MLA:
        MLA_INDEX: [2, 5, 8, 11]  # Base: [2, 5, 8, 11]; Large: [5, 11, 17, 23] 
        MLA_CHANNELS: 256
        MLAHEAD_CHANNELS: 128
        AUXIHEAD: False
TRAIN:
    BASE_LR: 0.001
    END_LR: 1e-4
    DECODER_LR_COEF: 10.0
    GRAD_CLIP: 1.0
    ITERS: 80000
    WEIGHT_DECAY: 0.0
    POWER: 0.9
    DECAY_STEPS: 80000
    LR_SCHEDULER:
        NAME: 'PolynomialDecay'
    OPTIMIZER:
        NAME: 'SGD'
        MOMENTUM: 0.9
VAL:
    MULTI_SCALES_VAL: False
    CROP_SIZE: [480,480]
SAVE_DIR: "./output/SETR_MLA_Base_480x480_80k_pascal_context_bs_16"


        

