DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: CrossViT
    NAME: crossvit_vit_base_224
    PARAMS:
        IMG_SIZE: [240, 224]
        PATCH_SIZE: [12, 16]
        EMBED_DIM: [384, 768]
        DEPTH: [[1, 4, 0], [1, 4, 0], [1, 4, 0]]
        NUM_HEADS: [12, 12]
        MLP_RATIO: [4, 4, 1]
        QKV_BIAS: True
#TRAIN:
#    NUM_EPOCHS: 300
#    WARMUP_EPOCHS: 3
#    WEIGHT_DECAY: 0.3
#    BASE_LR: 0.003
#    WARMUP_START_LR: 1e-6
#    END_LR: 5e-4
#    ACCUM_ITER: 2