DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: ConvMLP
    NAME: convmlp_l
    MIXER:
        BLOCKS: [4, 8, 3]
        DIMS: [192, 384, 768]
        MLP_RATIOS: [3, 3, 3]
        CHANNELS: 96
        N_CONV_BLOCKS: 3
