DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
    BATCH_SIZE: 1024
MODEL:
    TYPE: MAE
    NAME: vit_base_patch16_224
    TRANS:
        PATCH_SIZE: 16
        MLP_RATIO: 4.0
        QKV_BIAS: true
        MASK_RATIO: 0.75
        ENCODER:
            EMBED_DIM: 768
            DEPTH: 12
            NUM_HEADS: 12
        DECODER:
            EMBED_DIM: 512
            DEPTH: 8
            NUM_HEADS: 8
TRAIN:
    NUM_EPOCHS: 100
    WARMUP_EPOCHS: 5
    WEIGHT_DECAY: 0.05
    BASE_LR: 1e-3
    WARMUP_START_LR: 1e-6

    LR_SCHEDULER:
        NAME: 'warmupcosine'

    OPTIMIZER:
        NAME: 'AdamW'
        BETAS: (0.9, 0.999)
