DATA:
    IMAGE_SIZE: 256
    CROP_PCT: 0.875
MODEL:
    TYPE: MobileViT
    NAME: mobilevit_xxs
    DIMS: [16, 16, 24, 24, 24, 48, 64, 80, 320] # mobile v2 block output channels
    HIDDEN_DIMS: [64, 80, 96] # mobile vit block hidden dim
