DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.96
MODEL:
    TYPE: convmixer
    NAME: convmixer_1024_20
    CNN:
        DIM: 1024
        DEPTH: 20
        KERNEL_SIZE: 9 
        PATCH_SIZE: 14
        ACTIVATION: 'GELU'
