DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: ViP
    NAME: vip_s7
    MIXER:
        LAYER: [4, 3, 8, 3]
        TRANSITIONS: [True, False, False, False]
        SEGMENT_DIM: [32, 16, 16, 16]
        EMBED_DIMS: [192, 384, 384, 384]
