DATA:
    IMAGE_SIZE: 224
    CROP_PCT: 0.875
MODEL:
    TYPE: ViP
    NAME: vip_m7
    MIXER:
        LAYER: [4, 3, 14, 3]
        TRANSITIONS: [False, True, False, False]
        SEGMENT_DIM: [32, 32, 16, 16]
        EMBED_DIMS: [256, 256, 512, 512]
