DATA:
    DATASET: "Trans10K_cls12"
    BATCH_SIZE: 16
    BATCH_SIZE_VAL: 1
    DATA_PATH: 'E:/Trans10K_cls12'
    CROP_SIZE: (512, 512)
    NUM_CLASSES: 12
TRAIN:
    BASE_LR: 0.0001
    ITERS: 80000
    BASE_SIZE: 512
    LR_SCHEDULER:
        NAME: "PolynomialDecay"
    OPTIMIZER:
        NAME: 'ADAM'
VAL:
    MULTI_SCALES_VAL: False
    IMAGE_BASE_SIZE: 512
    CROP_SIZE: [512, 512]
    SCALE_RATIOS: [1.0]
MODEL:
    MODEL_NAME: "Trans2Seg"
    BACKBONE: "resnet50c"
    TRANS2Seg:
        embed_dim: 768
        depth: 12
        num_heads: 16
        mlp_ratio: 4.
        hid_dim: 128
AUG:
    CROP: False
SAVE_DIR: "./output/trans10kv2/trans2seg_large"