DATA:
    IMAGE_SIZE: 384
    CROP_PCT: 1.0
MODEL:
    TYPE: ViT
    NAME: vit_base_patch16_384
    TRANS:
        PATCH_SIZE: 16
        HIDDEN_SIZE: 768
        MLP_DIM: 3072 # same as mlp_ratio = 4.0
        NUM_LAYERS: 12
        NUM_HEADS: 12
        QKV_BIAS: true

