name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
        pip install yaml yacs 
        pip install cityscapesScripts detail
        pip install lmdb
        
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
